site_name: âœˆï¸NULL DOC
site_url: https://docs.papawall.cc


repo_name: PaPaWall/Doc
repo_url: https://github.com/papawall/padoc

theme:
    favicon: assets/logo.png
    logo: assets/googlelogo.png
    name: material
    #custom_dir: overrides/
    palette:
      scheme: default
      primary: white
    featuers:
      - search.highlight
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
      - navigation.instant
      - navigation.instant.preview
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - toc.follow
      - toc.integrate
      - header.autohide
      - announce.dismiss

    icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

plugins:
    - search
    - info
    - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      

nav:  #è¾¹ä¾§æ ç›®å½•
  - ğŸŒˆé¦–é¡µ: ./index.md
  - âš¡ç›®å½•: ./help/index.md
  - ğŸ“šæ•™ç¨‹:
    - ğŸ–¥ï¸Windowsæ•™ç¨‹: ./help/win/index.md
    - ğŸ’»Macæ•™ç¨‹: ./help/mac/index.md
    - ğŸ“±Androidæ•™ç¨‹: ./help/android/index.md
    - ğŸiOSæ•™ç¨‹: ./help/ios/index.md

extra:
    social:
      - icon: fontawesome/brands/telegram
        link: https://t.me/PaPaWall
      - icon: fontawesome/brands/internet-explorer
        link: https://papawall.pro
      - icon: fontawesome/brands/playstation
        link: https://t.me/PaPaWallInd
    homepage: https://docs.papawall.cc #logoé“¾æ¥
    generator: false #åˆ é™¤é¡µè„šç‰ˆæƒ

extra_css:
  - css/color.css  #é¡¶éƒ¨é¢œè‰²
  - css/donghua.css

copyright: |
  &copy 2017 - 2024 <a href="https://papawall.pro" target="_blank" rel="noopener">PaPa Wall Doc</a>

extra_javascript:
  - js/githubpl.js